### ISSUE TITLE
Add event emission on cage.

### ISSUE THREAD

**Issue by brianmcmichael** [makerdao/dss-gem-joins#23]
https://github.com/makerdao/dss-gem-joins/blob/374971aeaf4e6db854903462858790cfbfc15d6c/src/join-managed.sol#L65

**Comment by brianmcmichael** [comment]
`note` was removed here and was not replaced with an event call.

**Comment by talbaneth** [comment]
Done in https://github.com/makerdao/dss-gem-joins/pull/24
